#!/bin/bash
# PYTHON
alias py3='python3'
alias pip='pip3'
alias pip up='pip install --upgrade pip'
alias ve='python3 -m venv ./venv'
alias va='source ./venv/bin/activate'

# LINUX
alias ls='ls -G'
alias la='ls -aG'
alias ll='ls -lG'
alias c='clear'
alias t='touch'
alias tr='tree'
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
alias h='history'
alias b='bash'
alias f_file='find / -type f -name'
alias f_dir='find / -type d -name'
alias rmd='rm -rf'
alias diff='colordiff'
alias vd='vimdiff'
alias v='vim'
alias aliases='vim ~/.bash_aliases'
alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T"'
alias nowtime=now
alias nowdate='date +"%d-%m-%Y"'
alias df='df -H'
alias du='du -ch'
alias free='free -h'
alias meminfo='free -m -l -t'
alias ports='netstat -tulanp'

# GIT
alias g='git'
alias ga='git add'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -D'
alias gc='git commit -m'
alias gcl='git clone'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gcf='git config'
alias gd='git diff'
alias gi='git init'
alias gl='git log'
alias gf='git fetch'
alias gs='git status'
alias gss='git status -s'
alias gush='git push origin'
alias gull='git pull origin'

# DOCKER
alias d='docker'
alias db='docker build'
alias di='docker images'
alias ds='docker start'
alias dr='docker run'
alias dv='docker volume'
alias dc='docker-compose'
alias dcb='docker-compose build'
alias dcs='docker-compose start'
alias dcr='docker-compose run'
